 
{{- if .Values.appsConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "apps.fullname" . }}-config
  labels:
    app: "{{ template "apps.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- range $path, $config := .Values.appsConfig }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}